<?php

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Support\Facades\App;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }
    public function report(Throwable $e)
    {
        return parent::report($e); // TODO: Change the autogenerated stub
    }
    public function render($request, Throwable $e)
    {
        //return parent::render($request, $e); // TODO: Change the autogenerated stub
        if (app()->environment('test')) {
            if ($e instanceof \Illuminate\Database\Eloquent\ModelNotFoundException) {
                return response(view('errors.notice', [
                    'title'       => '찾을 수 없습니다.',
                    'description' => '죄송합니다! 요청하신 페이지가 없습니다.'
                ]), 404);
            }
        }
        return parent::render($request, $e);
    }
}
